name: r-spatial
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - rasterio
  - pyproj
  - shapely
  - xarray
  - zarr
  - netcdf4
  - fsspec
  - aiohttp
  - requests
  - tqdm
  - mgrs
  - pyshp
  - r-base
  - r-sf
  - r-terra
  - r-raster
  - r-sp
  - r-tidyverse
  - r-data.table
  - r-fst
  - r-tigris
  - r-readr
  - r-dplyr
  - r-tidyr
  - r-ggplot2
  - r-gridextra
  - r-jsonlite
  - r-magrittr
  - r-ncdf4
  - r-pbapply
  - r-pbmcapply
  - r-patchwork
  - r-rann
  - r-sandwich
  - r-scales
  - r-viridis
  - r-xtable
  - r-forestplot
  - r-dataverse
  - r-pROC
  - pip:
      - planetary-computer
      - pystac
      - umap-learn
